### ISSUE TITLE
[Feat] 후기 작성 모달 UI 구현

### ISSUE THREAD

**Issue by SHAKALOHANA** [SHAKALOHANA/codeit-FE10-GlobalNomad#31]
## 📝 Description

- 후기 작성 모달 구현

## ✅ To-Do List

- [ ] 헤더 / 모달창 닫기 아이콘
- [ ] activity bannerImage
- [ ] activity title
- [ ] 기간 / 예약 인원
- [ ] price
- [ ] 별 아이콘
- [ ] 후기 작성 textarea
- [ ] 작성하기 버튼
