### ISSUE TITLE
[Refactor] 내 정보 페이지 컴포넌트화 / 경로 및 파일명 변경

### ISSUE THREAD

**Issue by SHAKALOHANA** [SHAKALOHANA/codeit-FE10-GlobalNomad#33]
## 📝 Description

- 내 정보 페이지 컴포넌트화 / 경로 및 파일명 변경
- 예약 내역 리스트 파일명 변경

## ✅ To-Do List

**- 내 정보 페이지 컴포넌트화 / 경로 및 파일명 변경**
- [x] 변경 전 : /myPage/page.tsx
- [x] 변경 후 : /myPage/components/MyInfo.tsx
<br>

- [x] 변경 전 : /myPage/myPage.css.ts
- [x] 변경 후 : /myPage/components/MyInfo.css.ts

<br><br>
**- 예약 내역 리스트 파일명 변경**
- [x] 파일명 변경 전 :  reservationsList.tsx    
- [x] 파일명 변경 후 :  ReservationsList.tsx     (첫 글자 대문자로 - 파스칼케이스)
<br>

- [x] 파일명 변경 전 :  reservationsList.css.ts
- [x] 파일명 변경 후 :  ReservationsList.css.ts    (첫 글자 대문자로 - 파스칼케이스)
