### ISSUE TITLE
[feat] Footer제작

### ISSUE THREAD

**Issue by stella-418** [SHAKALOHANA/codeit-FE10-GlobalNomad#7]
## 📝 Description

- Footer 제작

## ✅ To-Do List

- [x] 템플릿 코드 참고하여 코드 작성
- [x] Footer용 아이콘 다운로드 및 적용
- [ ] Header 및 Footer 컴포넌트 관련 폴더 구조 상의
